/* 기존 테이블 삭제 (외래 키 제약 조건 고려하여 역순 삭제) */
DROP TABLE "ITEM_COMPATIBILITY" CASCADE CONSTRAINTS;
DROP TABLE "REPORT" CASCADE CONSTRAINTS;
DROP TABLE "INQUIRY" CASCADE CONSTRAINTS;
DROP TABLE "LIKE" CASCADE CONSTRAINTS;
DROP TABLE "LOL_BOARD" CASCADE CONSTRAINTS;
DROP TABLE "OVERWATCH_BOARD" CASCADE CONSTRAINTS;
DROP TABLE "BATTLEGROUND_BOARD" CASCADE CONSTRAINTS;
DROP TABLE "COMMENT" CASCADE CONSTRAINTS;
DROP TABLE "File" CASCADE CONSTRAINTS;
DROP TABLE "BOARD" CASCADE CONSTRAINTS;
DROP TABLE "WEAPON" CASCADE CONSTRAINTS;
DROP TABLE "EQUIPMENT" CASCADE CONSTRAINTS;
DROP TABLE "BAG_ITEM_INFO" CASCADE CONSTRAINTS;
DROP TABLE "BAG_ITEM_CATEGORY" CASCADE CONSTRAINTS;
DROP TABLE "ITEM_WEIGHT" CASCADE CONSTRAINTS;
DROP TABLE "ITEM_LIST" CASCADE CONSTRAINTS;
DROP TABLE "Box_LIST" CASCADE CONSTRAINTS;
DROP TABLE "MAP_MARKER" CASCADE CONSTRAINTS;
DROP TABLE "MAP_INFO" CASCADE CONSTRAINTS;
DROP TABLE "MARKER_CATEGORY" CASCADE CONSTRAINTS;
DROP TABLE "HERO_SKIN_INFO" CASCADE CONSTRAINTS;
DROP TABLE "HERO_INFO" CASCADE CONSTRAINTS;
DROP TABLE "CHAMP_SKIN_INFO" CASCADE CONSTRAINTS;
DROP TABLE "CHAMP_INFO" CASCADE CONSTRAINTS;
DROP TABLE "CopyOfRUNE_INFO" CASCADE CONSTRAINTS;
DROP TABLE "RUNE_INFO" CASCADE CONSTRAINTS;
DROP TABLE "Notice" CASCADE CONSTRAINTS;
DROP TABLE "PatchNote" CASCADE CONSTRAINTS;
DROP TABLE "USER" CASCADE CONSTRAINTS;
DROP TABLE "LOL_ITEM_INFO" CASCADE CONSTRAINTS;
DROP TABLE "SPELL_INFO" CASCADE CONSTRAINTS;

---

CREATE TABLE "SPELL_INFO" (
	"SPELL_NO"	NUMBER		NOT NULL,
	"SPELL_NAME"	VARCHAR2(20)		NULL,
	"SPELL_INFO"	VARCHAR2(200)		NULL,
    CONSTRAINT "PK_SPELL_INFO" PRIMARY KEY ("SPELL_NO")
);

CREATE TABLE "LOL_ITEM_INFO" (
	"ITEM_NO"	NUMBER		NOT NULL,
	"ITEM_NAME"	VARCHAR2(20)		NOT NULL,
	"ITEM_PRICE"	NUMBER		NOT NULL,
	"ITEM_INFO"	VARCHAR2(200)		NULL,
	"ITEM_IMG"	VARCHAR2(200)		NULL,
    CONSTRAINT "PK_LOL_ITEM_INFO" PRIMARY KEY ("ITEM_NO")
);

CREATE TABLE "USER" (
	"USER_ID"	VARCHAR2(20)		NOT NULL,
	"USER_PW"	NVARCHAR2(50)		NOT NULL,
	"USER_NAME"	VARCHAR2(30)		NOT NULL,
	"STATUS"	CHAR(1)	DEFAULT 'Y'	NOT NULL,
	"WITHDRAW"	NUMBER(1)		NOT NULL, -- bit(1) 대신 NUMBER(1) 사용
	"ENROLL_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"USER_ROLE"	CHAR(1)	DEFAULT 'U'	NOT NULL,
    CONSTRAINT "PK_USER" PRIMARY KEY ("USER_ID")
);

CREATE TABLE "BOARD" (
	"BOARD_NO"	NUMBER		NOT NULL,
	"USER_ID"	VARCHAR2(20)		NOT NULL,
	"USER_NAME"	VARCHAR2(30)		NOT NULL,
	"BOARD_CONTENT"	NVARCHAR2(500)		NOT NULL,
	"BOARD_TITLE"	NVARCHAR2(50)		NOT NULL,
	"POST_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"BOARD_CD"	CHAR(1)	DEFAULT 'Y'	NOT NULL,
    CONSTRAINT "PK_BOARD" PRIMARY KEY ("BOARD_NO")
);

CREATE TABLE "COMMENT" (
	"COMMENT_NO"	NUMBER		NOT NULL,
	"USER_ID"	VARCHAR2(20)		NOT NULL,
	"BOARD_NO"	NUMBER		NOT NULL,
	"USER_NAME"	VARCHAR2(30)		NOT NULL,
	"BOARD_CONTENT"	NVARCHAR2(200)		NOT NULL,
	"REPLY_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"STATUS"	CHAR(1)	DEFAULT 'Y'	NOT NULL,
    CONSTRAINT "PK_COMMENT" PRIMARY KEY ("COMMENT_NO")
);

CREATE TABLE "BAG_ITEM_CATEGORY" (
	"CATEGORY_NO"	NUMBER		NOT NULL,
	"CATEGORY_NAME"	VARCHAR2(100)		NOT NULL,
	"CATEGORY_IMG"	VARCHAR2(500)		NOT NULL,
    CONSTRAINT "PK_BAG_ITEM_CATEGORY" PRIMARY KEY ("CATEGORY_NO")
);

CREATE TABLE "BAG_ITEM_INFO" (
	"ITEM_NO"	NUMBER		NOT NULL,
	"CATEGORY_NO"	NUMBER		NOT NULL,
	"ITEM_NAME"	VARCHAR2(20)		NOT NULL,
	"ITEM_INFO"	VARCHAR2(200)		NULL,
	"ITEM_IMG"	VARCHAR2(500)		NULL,
	"ITEM_TYPE"	VARCHAR2(50)		NOT NULL,
    CONSTRAINT "PK_BAG_ITEM_INFO" PRIMARY KEY ("ITEM_NO", "CATEGORY_NO"),
    CONSTRAINT "FK_BAG_ITEM_CAT_TO_INFO" FOREIGN KEY ("CATEGORY_NO") REFERENCES "BAG_ITEM_CATEGORY"("CATEGORY_NO")
);

CREATE TABLE "WEAPON" (
	"ITEM_NO"	NUMBER		NOT NULL,
	"CATEGORY_NO"	NUMBER		NOT NULL,
	"ITEM_DAMAGE"	NUMBER		NOT NULL,
	"ITEM_AMMO_COUNT"	NUMBER		NOT NULL,
	"ITEM_AMMO_TYPE"	VARCHAR2(50)		NOT NULL,
    CONSTRAINT "PK_WEAPON" PRIMARY KEY ("ITEM_NO", "CATEGORY_NO"),
    CONSTRAINT "FK_BAG_ITEM_TO_WEAPON" FOREIGN KEY ("ITEM_NO", "CATEGORY_NO") REFERENCES "BAG_ITEM_INFO"("ITEM_NO", "CATEGORY_NO")
);

CREATE TABLE "EQUIPMENT" (
	"ITEM_NO"	NUMBER		NOT NULL,
	"CATEGORY_NO"	NUMBER		NOT NULL,
	"ITEM_DURABILITY"	NUMBER		NULL,
	"ITEM_DAMAGE_REDUCTION"	NUMBER		NULL,
    CONSTRAINT "PK_EQUIPMENT" PRIMARY KEY ("ITEM_NO", "CATEGORY_NO"),
    CONSTRAINT "FK_BAG_ITEM_TO_EQUIP" FOREIGN KEY ("ITEM_NO", "CATEGORY_NO") REFERENCES "BAG_ITEM_INFO"("ITEM_NO", "CATEGORY_NO")
);

CREATE TABLE "CHAMP_INFO" (
	"CHAMP_NO"	NUMBER		NOT NULL,
	"CHAMP_NAME"	VARCHAR2(20)		NOT NULL,
	"CHAMP_POSITION"	VARCHAR2(10)		NOT NULL,
	"CHAMP_ROLES"	VARCHAR2(10)		NULL,
	"CHAMP_IMG"	VARCHAR2(200)		NULL,
    CONSTRAINT "PK_CHAMP_INFO" PRIMARY KEY ("CHAMP_NO")
);

CREATE TABLE "CHAMP_SKIN_INFO" (
	"CHAMP_SKIN_NO"	NUMBER		NOT NULL,
	"CHAMP_NO"	NUMBER		NOT NULL,
	"CHAMP_SKIN_NAME"	VARCHAR2(20)		NOT NULL,
	"CHAMP_SKIN_IMG"	VARCHAR2(200)		NULL,
    CONSTRAINT "PK_CHAMP_SKIN_INFO" PRIMARY KEY ("CHAMP_SKIN_NO", "CHAMP_NO"),
    CONSTRAINT "FK_CHAMP_INFO_TO_SKIN" FOREIGN KEY ("CHAMP_NO") REFERENCES "CHAMP_INFO"("CHAMP_NO")
);

CREATE TABLE "HERO_INFO" (
	"HERO_NO"	NUMBER		NOT NULL,
	"HERO_NAME"	VARCHAR2(20)		NOT NULL,
	"HERO_INTRO"	VARCHAR2(100)		NULL,
	"HERO_HP"	NUMBER	DEFAULT 0	NOT NULL,
	"HERO_POSITION"	VARCHAR2(10)		NOT NULL,
    CONSTRAINT "PK_HERO_INFO" PRIMARY KEY ("HERO_NO")
);

CREATE TABLE "HERO_SKIN_INFO" (
	"HERO_SKIN_NO"	NUMBER		NOT NULL,
	"HERO_NO"	NUMBER		NOT NULL,
	"HERO_SKIN_NAME"	VARCHAR2(20)		NOT NULL,
	"HERO_SKIN_IMG"	VARCHAR2(200)		NULL,
    CONSTRAINT "PK_HERO_SKIN_INFO" PRIMARY KEY ("HERO_SKIN_NO", "HERO_NO"),
    CONSTRAINT "FK_HERO_INFO_TO_SKIN" FOREIGN KEY ("HERO_NO") REFERENCES "HERO_INFO"("HERO_NO")
);

CREATE TABLE "LOL_BOARD" (
	"BOARD_NO"	NUMBER		NOT NULL,
	"TITLE"	NVARCHAR2(50)		NOT NULL,
	"CATEGORY"	VARCHAR2(20)		NOT NULL,
	"USER_NAME"	VARCHAR2(30)		NOT NULL,
	"STATUS"	CHAR(1)		NOT NULL,
	"POST_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
    CONSTRAINT "PK_LOL_BOARD" PRIMARY KEY ("BOARD_NO"),
    CONSTRAINT "FK_BOARD_TO_LOL_BOARD" FOREIGN KEY ("BOARD_NO") REFERENCES "BOARD" ("BOARD_NO")
);

CREATE TABLE "OVERWATCH_BOARD" (
	"BOARD_NO"	NUMBER		NOT NULL,
	"TITLE"	NVARCHAR2(50)		NOT NULL,
	"CATEGORY"	VARCHAR2(20)		NOT NULL,
	"USER_NAME"	VARCHAR2(30)		NOT NULL,
	"STATUS"	CHAR(1)		NOT NULL,
	"POST_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
    CONSTRAINT "PK_OVERWATCH_BOARD" PRIMARY KEY ("BOARD_NO"),
    CONSTRAINT "FK_BOARD_TO_OW_BOARD" FOREIGN KEY ("BOARD_NO") REFERENCES "BOARD" ("BOARD_NO")
);

CREATE TABLE "BATTLEGROUND_BOARD" (
	"BOARD_NO"	NUMBER		NOT NULL,
	"TITLE"	NVARCHAR2(50)		NOT NULL,
	"CATEGORY"	VARCHAR2(20)		NOT NULL,
	"USER_NAME"	VARCHAR2(30)		NOT NULL,
	"STATUS"	CHAR(1)		NOT NULL,
	"POST_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
    CONSTRAINT "PK_BATTLEGROUND_BOARD" PRIMARY KEY ("BOARD_NO"),
    CONSTRAINT "FK_BOARD_TO_BG_BOARD" FOREIGN KEY ("BOARD_NO") REFERENCES "BOARD" ("BOARD_NO")
);

CREATE TABLE "ITEM_LIST" (
	"ITEM_NO"	NUMBER		NOT NULL,
	"ITEM_NAME"	VARCHAR2(100)		NOT NULL,
	"ITEM_GRADE"	VARCHAR2(20)		NOT NULL,
	"ITEM_TYPE"	VARCHAR2(50)		NOT NULL,
    CONSTRAINT "PK_ITEM_LIST" PRIMARY KEY ("ITEM_NO")
);

CREATE TABLE "Box_LIST" (
	"BOX_NO"	NUMBER		NOT NULL,
	"BOX_NAME"	VARCHAR2(100)		NOT NULL,
	"BOX_TYPE"	VARCHAR2(100)		NOT NULL,
	"START_DATE"	DATE		NOT NULL,
	"END_DATE"	DATE		NOT NULL,
    CONSTRAINT "PK_BOX_LIST" PRIMARY KEY ("BOX_NO")
);

CREATE TABLE "ITEM_WEIGHT" (
	"ITEM_NO"	NUMBER		NOT NULL,
	"POOL_NO"	NUMBER		NOT NULL,
	"WEIGHT"	NUMBER		NOT NULL,
    CONSTRAINT "PK_ITEM_WEIGHT" PRIMARY KEY ("ITEM_NO", "POOL_NO"),
    CONSTRAINT "FK_ITEM_LIST_TO_WEIGHT" FOREIGN KEY ("ITEM_NO") REFERENCES "ITEM_LIST"("ITEM_NO"),
    CONSTRAINT "FK_BOX_LIST_TO_WEIGHT" FOREIGN KEY ("POOL_NO") REFERENCES "Box_LIST"("BOX_NO")
);

CREATE TABLE "RUNE_INFO" (
	"RUNE_NO"	NUMBER		NOT NULL,
	"RUNE_NAME"	VARCHAR2(10)		NOT NULL,
	"Field"	VARCHAR2(50)		NULL,
	"RUNE_IMG"	VARCHAR2(200)		NULL,
    CONSTRAINT "PK_RUNE_INFO" PRIMARY KEY ("RUNE_NO")
);

CREATE TABLE "CopyOfRUNE_INFO" (
	"RUNE_NO"	NUMBER		NOT NULL,
	"RUNE_NO2"	NUMBER		NOT NULL,
	"TALENT_NAME"	VARCHAR2(10)		NOT NULL,
	"TALENT_INFO"	VARCHAR2(100)		NULL,
	"TALENT_IMG"	VARCHAR2(200)		NULL,
    CONSTRAINT "PK_COPYOFRUNE_INFO" PRIMARY KEY ("RUNE_NO", "RUNE_NO2"),
    CONSTRAINT "FK_RUNE_INFO_TO_COPY" FOREIGN KEY ("RUNE_NO2") REFERENCES "RUNE_INFO"("RUNE_NO")
);

CREATE TABLE "File" (
	"FILE_NO"	NUMBER		NOT NULL,
	"BOARD_NO"	NUMBER		NOT NULL,
	"ORIGIN_NAME"	VARCHAR2(255)		NOT NULL,
	"CHANGE_NAME"	VARCHAR2(255)		NOT NULL,
	"FILE_PATH"	VARCHAR2(500)		NOT NULL,
	"FILE_EXT"	VARCHAR2(50)		NOT NULL,
	"FILE_SIZE"	NUMBER		NOT NULL,
    CONSTRAINT "PK_FILE" PRIMARY KEY ("FILE_NO"),
    CONSTRAINT "FK_BOARD_TO_FILE" FOREIGN KEY ("BOARD_NO") REFERENCES "BOARD"("BOARD_NO")
);

CREATE TABLE "LIKE" (
	"LIKE_NO"	NUMBER		NOT NULL,
	"USER_ID"	VARCHAR2(20)		NOT NULL,
	"BOARD_NO"	NUMBER		NOT NULL,
    CONSTRAINT "PK_LIKE" PRIMARY KEY ("LIKE_NO"),
    CONSTRAINT "FK_USER_TO_LIKE" FOREIGN KEY ("USER_ID") REFERENCES "USER"("USER_ID"),
    CONSTRAINT "FK_BOARD_TO_LIKE" FOREIGN KEY ("BOARD_NO") REFERENCES "BOARD"("BOARD_NO")
);

CREATE TABLE "REPORT" (
	"REPORT_BOARD_NO"	VARCHAR2(255)		NOT NULL,
	"CONTENT"	VARCHAR2(255)		NOT NULL,
	"DONE_DATE"	DATE	DEFAULT SYSDATE	NULL,
	"USER_ID"	VARCHAR2(20)		NOT NULL,
	"USER_ROLE"	CHAR(1)	DEFAULT 'U'	NULL,
	"BOARD_NO"	NUMBER		NOT NULL,
	"COMMENT_NO"	NUMBER		NOT NULL,
    CONSTRAINT "PK_REPORT" PRIMARY KEY ("REPORT_BOARD_NO"),
    CONSTRAINT "FK_USER_TO_REPORT" FOREIGN KEY ("USER_ID") REFERENCES "USER"("USER_ID"),
    CONSTRAINT "FK_BOARD_TO_REPORT" FOREIGN KEY ("BOARD_NO") REFERENCES "BOARD"("BOARD_NO"),
    CONSTRAINT "FK_COMMENT_TO_REPORT" FOREIGN KEY ("COMMENT_NO") REFERENCES "COMMENT"("COMMENT_NO")
);

CREATE TABLE "INQUIRY" (
	"BOARD_NO"	NUMBER		NOT NULL,
	"USER_ID"	VARCHAR2(20)		NOT NULL,
	"USER_NAME"	VARCHAR2(30)		NOT NULL,
	"BOARD_CONTENT"	NVARCHAR2(500)		NOT NULL,
	"BOARD_TITLE"	NVARCHAR2(50)		NOT NULL,
	"POST_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"ANS_STATUS"	CHAR(1)	DEFAULT 'W'	NOT NULL,
    CONSTRAINT "PK_INQUIRY" PRIMARY KEY ("BOARD_NO"),
    CONSTRAINT "FK_USER_TO_INQUIRY" FOREIGN KEY ("USER_ID") REFERENCES "USER"("USER_ID")
);

CREATE TABLE "Notice" (
	"NOTICE_NO"	VARCHAR2(10)		NOT NULL,
	"TITLE"	VARCHAR2(100)		NOT NULL,
	"POST_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"NOTICE_CONTENT"	VARCHAR2(100)		NOT NULL,
    CONSTRAINT "PK_NOTICE" PRIMARY KEY ("NOTICE_NO")
);

CREATE TABLE "PatchNote" (
	"PATCHNOTE_NO"	VARCHAR2(10)		NOT NULL,
	"TITLE"	VARCHAR2(100)		NOT NULL,
	"POST_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"PATCHNOTE_CONTENT"	VARCHAR2(2000)		NOT NULL,
    CONSTRAINT "PK_PATCHNOTE" PRIMARY KEY ("PATCHNOTE_NO")
);

CREATE TABLE "MAP_INFO" (
	"MAP_NO"	NUMBER		NOT NULL,
	"MAP_NAME"	VARCHAR2(50)		NOT NULL,
	"MAP_IMG"	VARCHAR2(500)		NOT NULL,
    CONSTRAINT "PK_MAP_INFO" PRIMARY KEY ("MAP_NO")
);

CREATE TABLE "MARKER_CATEGORY" (
	"CATEGORY_NO"	NUMBER		NOT NULL,
	"CATEGORY_NAME"	VARCHAR2(100)		NOT NULL,
    CONSTRAINT "PK_MARKER_CATEGORY" PRIMARY KEY ("CATEGORY_NO")
);

CREATE TABLE "MAP_MARKER" (
	"MARKER_NO"	NUMBER		NOT NULL,
	"COORD_X"	NUMBER		NOT NULL,
	"COORD_Y"	NUMBER		NOT NULL,
	"MARKER_IMG"	VARCHAR2(500)		NOT NULL,
	"MAP_NO"	NUMBER		NOT NULL,
	"CATEGORY_NO"	NUMBER		NOT NULL,
    CONSTRAINT "PK_MAP_MARKER" PRIMARY KEY ("MARKER_NO"),
    CONSTRAINT "FK_MAP_TO_MARKER" FOREIGN KEY ("MAP_NO") REFERENCES "MAP_INFO"("MAP_NO"),
    CONSTRAINT "FK_CAT_TO_MARKER" FOREIGN KEY ("CATEGORY_NO") REFERENCES "MARKER_CATEGORY"("CATEGORY_NO")
);

CREATE TABLE "ITEM_COMPATIBILITY" (
	"ITEM_NO"	NUMBER		NOT NULL,
	"CATEGORY_NO"	NUMBER		NOT NULL,
	"PART_ITEM_NO"	NUMBER		NOT NULL,
	"PART_CATEGORY_NO"	NUMBER		NOT NULL,
	"WEAPON_ITEM_NO"	NUMBER		NOT NULL,
	"WEAPON_CATEGORY_NO"	NUMBER		NOT NULL,
    CONSTRAINT "FK_BAG_ITEM_TO_COMPAT" FOREIGN KEY ("ITEM_NO", "CATEGORY_NO") REFERENCES "BAG_ITEM_INFO"("ITEM_NO", "CATEGORY_NO")
);

/* 주석 생략 없이 그대로 유지 (일부 예시) */
COMMENT ON COLUMN "BOARD"."BOARD_NO" IS '시퀀스 자동생성';
COMMENT ON COLUMN "USER"."WITHDRAW" IS '탈퇴여부(0:유지, 1:탈퇴)';