-- 기존 제약 조건 및 테이블 삭제 (외래 키 때문에 삭제 순서가 중요함)
DROP TABLE "ITEM_WEIGHT" CASCADE CONSTRAINTS;
DROP TABLE "ITEM_LIST" CASCADE CONSTRAINTS;
DROP TABLE "Box" CASCADE CONSTRAINTS;
DROP TABLE "COMMENT" CASCADE CONSTRAINTS;
DROP TABLE "BOARD" CASCADE CONSTRAINTS;
DROP TABLE "BATTLEGROUND_BOARD" CASCADE CONSTRAINTS;
DROP TABLE "OVERWATCH_BOARD" CASCADE CONSTRAINTS;
DROP TABLE "LOL_BOARD" CASCADE CONSTRAINTS;
DROP TABLE "REPORT" CASCADE CONSTRAINTS;
DROP TABLE "USER" CASCADE CONSTRAINTS;
DROP TABLE "Untitled" CASCADE CONSTRAINTS;
DROP TABLE "CopyOfUntitled" CASCADE CONSTRAINTS;

---

CREATE TABLE "CopyOfUntitled" (
	"Field"	VARCHAR2(255)		NULL
);

CREATE TABLE "Untitled" (
	"NOTICE_NUM"	VARCHAR2(10)		NOT NULL,
	"TITLE"	VARCHAR2(50)		NOT NULL,
	"WRITE_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"Field"	VARCHAR2(255)		NULL,
	"USER_ID"	VARCHAR2(20)		NOT NULL,
    CONSTRAINT "PK_UNTITLED" PRIMARY KEY ("NOTICE_NUM")
);

COMMENT ON COLUMN "Untitled"."NOTICE_NUM" IS '공지사항번호';
COMMENT ON COLUMN "Untitled"."TITLE" IS '글 제목';
COMMENT ON COLUMN "Untitled"."WRITE_DATE" IS '디폴트 : SYSDATE';
COMMENT ON COLUMN "Untitled"."USER_ID" IS '아이디(PK)';

CREATE TABLE "USER" (
	"USER_ID"	VARCHAR2(20)		NOT NULL,
	"USER_PW"	NVARCHAR2(50)		NOT NULL,
	"USER_NAME"	VARCHAR2(50)		NOT NULL, -- 크기 지정 필요
	"STATUS"	CHAR(1)	DEFAULT 'Y'	NOT NULL, -- 문자열 리터럴 'Y'로 수정
	"WITHDRAW"	NUMBER(1)		NOT NULL, -- bit(1)은 오라클에 없음, NUMBER(1)로 대체
	"ENROLL_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
    CONSTRAINT "PK_USER" PRIMARY KEY ("USER_ID")
);

COMMENT ON COLUMN "USER"."USER_ID" IS '아이디(PK)';
COMMENT ON COLUMN "USER"."USER_PW" IS '비밀번호';
COMMENT ON COLUMN "USER"."USER_NAME" IS '닉네임';
COMMENT ON COLUMN "USER"."STATUS" IS '로그인 Y , N';
COMMENT ON COLUMN "USER"."WITHDRAW" IS '탈퇴여부';
COMMENT ON COLUMN "USER"."ENROLL_DATE" IS '디폴트 : SYSDATE';

CREATE TABLE "REPORT" (
	"Field"	VARCHAR2(255)		NULL,
	"Field2"	VARCHAR2(255)		NULL,
	"Field3"	VARCHAR2(255)		NULL
);

CREATE TABLE "LOL_BOARD" (
	"BOARD_NO"	NUMBER		NOT NULL,
	"USER_PW"	NVARCHAR2(50)		NOT NULL,
	"USER_NAME"	VARCHAR2(50)		NOT NULL,
	"STATUS"	CHAR(1)		NOT NULL,
	"ENROLL_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"Field"	VARCHAR2(255)		NULL,
    CONSTRAINT "PK_LOL_BOARD" PRIMARY KEY ("BOARD_NO")
);

COMMENT ON COLUMN "LOL_BOARD"."BOARD_NO" IS '시퀀스 자동생성';
COMMENT ON COLUMN "LOL_BOARD"."USER_PW" IS '비밀번호';
COMMENT ON COLUMN "LOL_BOARD"."USER_NAME" IS '닉네임';
COMMENT ON COLUMN "LOL_BOARD"."STATUS" IS '로그인 유무, 탈퇴';
COMMENT ON COLUMN "LOL_BOARD"."ENROLL_DATE" IS '디폴트 : SYSDATE';

CREATE TABLE "ITEM_LIST" (
	"ITEM_NO"	NUMBER		NOT NULL,
	"ITEM_NAME"	VARCHAR2(100)		NOT NULL,
	"ITEM_GRADE"	VARCHAR2(20)		NOT NULL,
	"ITEM_TYPE"	VARCHAR2(50)		NOT NULL,
    CONSTRAINT "PK_ITEM_LIST" PRIMARY KEY ("ITEM_NO")
);

CREATE TABLE "OVERWATCH_BOARD" (
	"USER_PW"	NVARCHAR2(50)		NOT NULL,
	"USER_NAME"	VARCHAR2(50)		NOT NULL,
	"STATUS"	CHAR(1)		NOT NULL,
	"ENROLL_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"Field"	VARCHAR2(255)		NULL
);

CREATE TABLE "BATTLEGROUND_BOARD" (
	"USER_PW"	NVARCHAR2(50)		NOT NULL,
	"USER_NAME"	VARCHAR2(50)		NOT NULL,
	"STATUS"	CHAR(1)		NOT NULL,
	"ENROLL_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"Field"	VARCHAR2(255)		NULL
);

CREATE TABLE "BOARD" (
	"BOARD_NO"	NUMBER		NOT NULL,
	"USER_ID"	VARCHAR2(20)		NOT NULL,
	"USER_NAME"	VARCHAR2(50)		NOT NULL,
	"BOARD_CONTENT"	NVARCHAR2(500)		NOT NULL,
	"BOARD_TITLE"	NVARCHAR2(50)		NOT NULL,
	"POST_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"Field5"	VARCHAR2(255)		NULL,
	"Field6"	VARCHAR2(255)		NULL,
    CONSTRAINT "PK_BOARD" PRIMARY KEY ("BOARD_NO")
);

CREATE TABLE "Box" (
	"POOL_NO"	NUMBER		NOT NULL,
	"POOL_NAME"	VARCHAR2(100)		NOT NULL,
	"START_DATE"	DATE		NOT NULL,
	"END_DATE"	DATE		NOT NULL,
    CONSTRAINT "PK_BOX" PRIMARY KEY ("POOL_NO")
);

CREATE TABLE "ITEM_WEIGHT" (
	"ITEM_NO"	NUMBER		NOT NULL,
	"POOL_NO2"	NUMBER		NOT NULL,
	"WEIGHT"	NUMBER		NOT NULL,
    CONSTRAINT "PK_ITEM_WEIGHT" PRIMARY KEY ("ITEM_NO", "POOL_NO2")
);

CREATE TABLE "COMMENT" (
	"COMMENT_NO"	NUMBER		NOT NULL,
	"USER_ID"	VARCHAR2(20)		NOT NULL,
	"USER_NAME"	VARCHAR2(50)		NOT NULL,
	"BOARD_CONTENT"	NVARCHAR2(200)		NOT NULL,
	"BOARD_TITLE"	NVARCHAR2(50)		NOT NULL,
	"Field4"	VARCHAR2(255)		NULL,
	"Field5"	VARCHAR2(255)		NULL,
	"Field6"	VARCHAR2(255)		NULL,
    CONSTRAINT "PK_COMMENT" PRIMARY KEY ("COMMENT_NO")
);

-- 외래 키 설정
ALTER TABLE "ITEM_WEIGHT" ADD CONSTRAINT "FK_ITEM_LIST_TO_ITEM_WEIGHT_1" FOREIGN KEY ("ITEM_NO") REFERENCES "ITEM_LIST" ("ITEM_NO");
ALTER TABLE "ITEM_WEIGHT" ADD CONSTRAINT "FK_Box_TO_ITEM_WEIGHT_1" FOREIGN KEY ("POOL_NO2") REFERENCES "Box" ("POOL_NO");